version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./bnls_2022:/var/www/html/public/bnls_2022
      - ./bnls_2023:/var/www/html/public/bnls_2023
    environment:
      SYMFONY_ENV: prod
