version: '3.4'

x-images-volume:
  &images-volume
  type: bind
  source: ./bnls
  target: /var/www/bnls
x-images-2022-volume:
  &images-2022-volume
  type: bind
  source: ./bnls_2022
  target: /var/www/bnls_2022
x-images-2023-volume:
  &images-2023-volume
  type: bind
  source: ./bnls_2023
  target: /var/www/bnls_2023
x-images-2024-volume:
  &images-2024-volume
  type: bind
  source: ./bnls_2024
  target: /var/www/bnls_2024
x-images-2025-volume:
  &images-2025-volume
  type: bind
  source: ./bnls_2025
  target: /var/www/bnls_2025

services:
  server:
    image: nginx:1.17-alpine
    ports:
      - ${PORT}:80
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
      - static_content:/var/www/html/
      - *images-volume
      - *images-2022-volume
      - *images-2023-volume
      - *images-2024-volume
      - *images-2025-volume
    depends_on:
      - php-fpm
    links:
      - php-fpm
    restart: always

  php-fpm:
    image: 10.62.181.2:5000/bnls_images
    environment:
      APP_ENV: "prod"
      ENV_SUBSTITUTION_ENABLE: "true"
      PHP_MEMORY_LIMIT: "512M"
      PHP_FPM_LISTEN: 9090
      PHP_SESSION_GC_MAXLIFETIME: 7200
    expose:
      - 9090
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini"
      - static_content:/var/www/html/
      - *images-volume
      - *images-2022-volume
      - *images-2023-volume
      - *images-2024-volume
      - *images-2025-volume
    restart: always

volumes:
  static_content:
